### ISSUE TITLE
Error in download_scdb()

### ISSUE THREAD

**Issue by bill10** [idc9/law-net#7]
the to_csv() function in pandas doesn't seem to have "index_col" as its parameter. See the error message below. 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-1401de815a4c> in <module>()
----> 1 download_scdb(data_dir)

/home/bill10/Research/Law_Networks/law-net/code/pipeline/download_data.py in download_scdb(data_dir)
    165     # download data from scdb
    166     scdb_modern_url = 'http://scdb.wustl.edu/_brickFiles/2016_01/SCDB_2016_01_caseCentered_Citation.csv.zip'
--> 167     download_zip_to_csv(scdb_modern_url, data_dir + 'scdb/')
    168     scdb_legacy_url = 'http://scdb.wustl.edu/_brickFiles/Legacy_03/SCDB_Legacy_03_caseCentered_Citation.csv.zip'
    169     download_zip_to_csv(scdb_legacy_url, data_dir + 'scdb/')

/home/bill10/Research/Law_Networks/law-net/code/pipeline/download_data.py in download_zip_to_csv(url, path)
    237 
    238     # save csv
--> 239     data.to_csv(zip_path.split('.zip')[0], index_col=0)
    240 
    241     # kill the zip file

TypeError: to_csv() got an unexpected keyword argument 'index_col'`

**Comment by idc9** [comment]
Fixed -- it was supposed to be `, index=True)`

**Comment by bill10** [comment]
Thank you!
